vulnerable(disparo(humano),ia).
vulnerable(asteroide_gris,ia).
vulnerable(disparo(ia),humano).
vulnerable(asteroide,humano).
vulnerable(asteroide,ia).
vulnerable(disparo(ia),disparo(humano)).
vulnerable(disparo(ia),asteroide).
vulnerable(disparo(humano),ia(doubleshot)).
vulnerable(asteroide_gris,humano).
invulnerable(disparo(ia),asteroide_gris).
invulnerable(disparo(ia),humano(shield)).
invulnerable(disparo(humano),ia(shield)).
mejora(power_up(shield),humano).
mejora(power_up(augmentedbullet),humano).
mejora(power_up(augmentedbullet),ia).
mejora(power_up(shield),ia).
mejora(power_up(doubleshot),ia).
destruible(ia).
destruible(humano).
destruible(disparo(humano)).
destruible(asteroide).
destruible(ia(doubleshot)).
